server:
  port: 8767

spring:
  application:
    name: spring-cloud-consumer-movie-feign
    
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
user: 
  userServicePath: http://localhost:8762/simple/
  
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
