server:
  port: 8766

spring:
  application:
    name: spring-cloud-consumer-movie-ribbon-without-eureka
    
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
ribbon:
  eureka:
   enabled: false  #设置space中eureka不可获得
spring-cloud-provider-user:  #设置需要负载的服务名称
  ribbon:
    listOfServers: localhost:8762,localhost:8763 #设置需要负载的服务地址