server:
  port: 8766

spring:
  application:
    name: spring-cloud-consumer-movie-ribbon
    
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
spring-cloud-provider-user:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule  相应时间加权，便已测试使用randomRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule