spring:
  application:
    name: spring-cloud-gateway-zuul-fallback
server:
  port: 8740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    prefer-ip-address: true
    
zuul:
  routes:
    users: # 这个users可以随便写  abc都可以
      path: /users/**
      service-id: spring-cloud-provider-user