server:
  port: 8980
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oyidZh/SpringCloudConfigFile
  application:
    name: spring-cloud-config-server-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:linkage@localhost:8761/eureka/
  instance:
    prefer-ip-address: true     
      
  
  
