server:
  port: 8765

spring:
  application:
    name: spring-cloud-consumer-movie-ribbon-test
    
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    